### ISSUE TITLE
Add bios to project

### ISSUE THREAD

**Issue by hubyeti** [sparraguerra/github-for-developers-7#3]
We should all create great bios in this project. Make sure your bio includes:

         - [ ] Your name
         - [ ] Where you are from
         - [ ] A favorite food
         - [ ] A hobby

**Comment by sparraguerra** [comment]
## My Bio

- [x] Your Name:  Sergio Parra Guerra
- [x] Where you are from:    Spain
- [x] A favourite food:    Spaghetti
- [x] A hobby: Programming
